/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista documentos com paginação por cursor */
        get: {
            parameters: {
                query?: {
                    estado?: components["schemas"]["EstadoDocumento"];
                    cursor?: string;
                    limite?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Página de documentos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginaDeDocumentos"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Envia um documento para processamento
         * @description Responde **202** com o documento em `RECEBIDO`. O processamento é
         *     assíncrono; acompanhe por `GET /documentos/status`.
         *
         *     Se `contentHash` já existir, responde **200** com `duplicado: true` e o
         *     documento existente. **Nenhuma chamada ao modelo é disparada** — é o
         *     tratamento do fato (c) combinado com o custo do fato (a).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        arquivo: string;
                        /** @description SHA-256 do conteúdo, calculado no cliente */
                        contentHash: string;
                        /**
                         * @description Nome como o arquivo chegou. Metadado de origem, nunca
                         *     identificador.
                         * @example WhatsApp Image 2026-08-11 at 09.12.33.jpeg
                         */
                        nomeOrigem: string;
                    };
                };
            };
            responses: {
                /** @description Documento duplicado — já existia */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaEnvio"];
                    };
                };
                /** @description Aceito para processamento */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RespostaEnvio"];
                    };
                };
                413: components["responses"]["Problema"];
                415: components["responses"]["Problema"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de vários documentos numa única requisição
         * @description Existe por causa do fato (e). Com 800 documentos em acompanhamento, um
         *     polling por documento geraria centenas de requisições por segundo
         *     vindas de um único navegador.
         */
        get: {
            parameters: {
                query: {
                    ids: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estados */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            itens: components["schemas"]["StatusResumido"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Consulta um documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documento */
                200: {
                    headers: {
                        /** @description Versão, para uso em `If-Match` */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Documento"];
                    };
                };
                404: components["responses"]["Problema"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}/arquivo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * URL assinada e de curta duração do arquivo original
         * @description Nunca devolve URL permanente. Tratamento do fato (d): a imagem é
         *     efêmera para o cliente, e um link vazado expira sozinho.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description URL temporária */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            /** Format: date-time */
                            expiraEm: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocessa um documento — ação explícita e cobrada
         * @description **Nunca chamada automaticamente pelo cliente.** Cada execução custa uma
         *     chamada ao modelo (fato a). A interface exige confirmação humana que
         *     informa o custo antes de acionar.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reprocessamento aceito */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Documento"];
                    };
                };
                /** @description Estado não permite reprocessamento */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}/conferencia/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserva o documento para conferência
         * @description Tratamento do fato (g), parte 1 — evita que duas pessoas confiram o
         *     mesmo documento. A reserva expira sozinha por TTL, porque a aba fechada
         *     sem aviso é o caso normal, não a exceção.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reserva concedida ou renovada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                /** @description Já reservado por outra pessoa */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problema"];
                    };
                };
            };
        };
        /** Libera a reserva */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liberada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}/campos": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Versão do documento como carregada pelo cliente. Tratamento do fato
                 *     (g), parte 2 — impede que a gravação de uma pessoa apague em silêncio
                 *     a da outra.
                 */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Grava correções e conclui a conferência */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Versão do documento como carregada pelo cliente. Tratamento do fato
                     *     (g), parte 2 — impede que a gravação de uma pessoa apague em silêncio
                     *     a da outra.
                     */
                    "If-Match": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        campos: {
                            chave: string;
                            valor: string | null;
                        }[];
                        /** @description Editável pelo conferente (premissa P4) */
                        nomePadronizado?: string;
                    };
                };
            };
            responses: {
                /** @description Gravado; documento vai para PRONTO */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Documento"];
                    };
                };
                /**
                 * @description Conflito de versão. O corpo traz o documento atual para que a
                 *     interface mostre o que mudou e **quem** mudou. O cliente nunca
                 *     resolve sozinho.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemaDeConflito"];
                    };
                };
                412: components["responses"]["Problema"];
            };
        };
        trace?: never;
    };
    "/documentos/{id}/rejeitar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejeita o documento com motivo
         * @description Derivado do fato (b) — uma foto ilegível precisa ter saída do sistema.
         *     Rejeitar **não** dispara reprocessamento.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        motivo: "ILEGIVEL" | "TIPO_INCORRETO" | "INCOMPLETO" | "NAO_E_DOCUMENTO" | "OUTRO";
                        observacao?: string;
                    };
                };
            };
            responses: {
                /** @description Rejeitado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Documento"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipos-documento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de tipos e seus schemas de campo
         * @description **O endpoint que sustenta o fato (f).** O front-end não conhece nenhum
         *     tipo de documento; ele os recebe daqui, com rótulos, tipos de dado,
         *     máscaras, obrigatoriedade e ordem. Adicionar um tipo novo ao produto é
         *     mudança de zero linhas no front-end.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catálogo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            itens: components["schemas"]["TipoDocumento"][];
                            /**
                             * @description O limiar mora aqui, e não no front-end, porque será
                             *     calibrado com uso real — e calibrar não pode exigir
                             *     deploy da interface.
                             */
                            limiarConfiancaPadrao: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        EstadoDocumento: "RECEBIDO" | "EM_PROCESSAMENTO" | "AGUARDANDO_CONFERENCIA" | "EM_CONFERENCIA" | "PRONTO" | "FALHOU" | "EXPIRADO" | "REJEITADO";
        /**
         * @description Seis tipos de dado contra N tipos de documento. É essa razão que torna
         *     barata a troca prevista no fato (f).
         * @enum {string}
         */
        TipoDeDado: "TEXTO" | "DATA" | "CPF" | "CNPJ" | "NUMERO" | "SELECAO";
        Documento: {
            /** @description Identificador opaco. Nunca um dado pessoal */
            id: string;
            /** @description SHA-256. A identidade real do documento */
            contentHash: string;
            /** @description Como chegou. Metadado */
            nomeOrigem: string;
            nomePadronizado?: string | null;
            tipoDocumentoId?: string | null;
            estado: components["schemas"]["EstadoDocumento"];
            confianca?: number | null;
            campos: components["schemas"]["CampoExtraido"][];
            /** @description Trava otimista; vai no If-Match */
            versao: number;
            reserva?: components["schemas"]["Reserva"];
            procedencia?: components["schemas"]["Procedencia"];
            /** Format: date-time */
            recebidoEm: string;
            motivoFalha?: string | null;
        };
        CampoExtraido: {
            chave: string;
            valor: string | null;
            confianca: number;
            /**
             * @description Vira HUMANO quando corrigido na conferência
             * @enum {string}
             */
            origem: "MODELO" | "HUMANO";
        };
        TipoDocumento: {
            id: string;
            /** @description Texto exibido. Vem da API — o front não traduz */
            rotulo: string;
            /** @description Sobrepõe o padrão. Um RG extrai melhor que um contracheque amassado */
            limiarConfianca?: number | null;
            /** @description Modelo com as chaves dos campos, ex.: {tipo}_{nome}_{numero} */
            padraoDeNome?: string | null;
            campos: components["schemas"]["DescritorDeCampo"][];
        };
        DescritorDeCampo: {
            chave: string;
            rotulo: string;
            tipoDeDado: components["schemas"]["TipoDeDado"];
            obrigatorio: boolean;
            mascara?: string | null;
            ordem: number;
            /**
             * @description Se verdadeiro, mascarado na listagem (fato d)
             * @default false
             */
            sensivel: boolean;
            /** @description Apenas para SELECAO */
            opcoes?: string[];
        };
        Reserva: {
            usuarioId: string;
            /** @description Nulo quando o host não envia identidade */
            usuarioNome?: string | null;
            /** Format: date-time */
            expiraEm: string;
        } | null;
        Procedencia: {
            /** @example fornecedor-vision-2.1 */
            modelo: string;
            /** @example rg-v4 */
            versaoPrompt: string;
            /** Format: date-time */
            processadoEm?: string;
        };
        RespostaEnvio: {
            documento: components["schemas"]["Documento"];
            /**
             * @description Verdadeiro quando o contentHash já existia. Nenhum processamento
             *     novo foi disparado, e portanto nenhum custo foi gerado.
             */
            duplicado: boolean;
        };
        StatusResumido: {
            id: string;
            estado: components["schemas"]["EstadoDocumento"];
            versao: number;
            confianca?: number | null;
        };
        PaginaDeDocumentos: {
            itens: components["schemas"]["Documento"][];
            /** @description Cursor, não offset — a fila muda enquanto é paginada */
            proximoCursor?: string | null;
        };
        /** @description RFC 9457 */
        Problema: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        ProblemaDeConflito: components["schemas"]["Problema"] & {
            documentoAtual?: components["schemas"]["Documento"];
            alteradoPor?: string | null;
        };
    };
    responses: {
        /** @description Erro em RFC 9457 */
        Problema: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
